.PHONY: clean All

All:
	@echo "----------Building project:[ AdaptiveKuramotoOscillators - Debug ]----------"
	@cd "AdaptiveKuramotoOscillators" && "$(MAKE)" -f  "AdaptiveKuramotoOscillators.mk"
clean:
	@echo "----------Cleaning project:[ AdaptiveKuramotoOscillators - Debug ]----------"
	@cd "AdaptiveKuramotoOscillators" && "$(MAKE)" -f  "AdaptiveKuramotoOscillators.mk" clean
